### ISSUE TITLE
执行命令 python3.6 manage.py qt4i.setup  失败

### ISSUE THREAD

**Issue by uniapp10** [Tencent/QT4i#17]
以下是报错信息：

```
Traceback (most recent call last):
  File "manage.py", line 24, in <module>
    ManagementTools().run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/testbase/management.py", line 687, in run
    cmds = self._load_cmds()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/testbase/management.py", line 640, in _load_cmds
    cmds += self._load_cmd_from_module(sys.modules[__name__])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/testbase/management.py", line 663, in _load_cmd_from_module
    cmds.sort(lambda x, y:cmp_func(x.name, y.name))
TypeError: must use keyword argument for key function


```

**Comment by JerryGinger** [comment]
使用`qt4i-manage setup`命令试试

**Comment by guyingzhao** [comment]
应该是bug，预计下个版本修复

**Comment by JerryGinger** [comment]
This is a issue of [QTAF](https://github.com/tencent/qtaf).
