### ISSUE TITLE
qt4i-manage listdevices  报错

### ISSUE THREAD

**Issue by maiverson** [Tencent/QT4i#25]
$  qt4i-manage listdevices
Traceback (most recent call last):
  File "/Users/mac/.local/bin/qt4i-manage", line 10, in <module>
    sys.exit(qt4i_manage_main())
  File "/Users/mac/.local/lib/python3.7/site-packages/qt4i/cmds.py", line 241, in qt4i_manage_main
    subcmd.execute(args)
  File "/Users/mac/.local/lib/python3.7/site-packages/qt4i/cmds.py", line 108, in execute
    for device in DT().get_devices():
  File "/Users/mac/.local/lib/python3.7/site-packages/qt4i/driver/tools/dt.py", line 273, in get_devices
    return self._get_device_by_fbsimctl()
  File "/Users/mac/.local/lib/python3.7/site-packages/qt4i/driver/tools/dt.py", line 1003, in _get_device_by_fbsimctl
    name = dev['name']
TypeError: string indices must be integers

**Comment by JerryGinger** [comment]
更新qt4i版本
